Main page
LeontevV/leontev_final_front pull request #1
Opened 2022-06-02 07:09 UTC by LeontevV

2022-06-02 12:48 UTC, ekaterinagaltsova commented on src/App.js
> +
для кого пустышка?

2022-06-02 12:48 UTC, ekaterinagaltsova commented on src/components/Button/Button.jsx
> +export default function DisableElevation() {
?

2022-06-02 12:49 UTC, ekaterinagaltsova commented on src/pages/MainPage/MainPage.jsx
> +// import CircularProgress from '../../components/Spinner/Spinner';
не нужно закомментированного

2022-06-02 12:49 UTC, ekaterinagaltsova commented on src/redux/action/index.js
> +export const getPosts = () => ({
после импортов - пустая строка

2022-06-02 13:36 UTC, ekaterinagaltsova commented on src/App.jsx
> +// import UserPage from './pages/UserPage/UserPage';
закомменченое

2022-06-02 13:39 UTC, ekaterinagaltsova commented on src/components/Header/Header.jsx
> +import News2 from '../../assets/news2.png'
а есть 1?

2022-06-02 13:40 UTC, ekaterinagaltsova commented on src/pages/MainPage/MainPage.jsx
> +// import CircularProgress from '../../components/Spinner/';
закомменченное

2022-06-02 13:41 UTC, ekaterinagaltsova commented on src/App.jsx
>          {/* <Route path="/users/:id" element={<UserPage />} /> */}
закомменченое

2022-06-02 13:42 UTC, ekaterinagaltsova commented on src/api/api.js
> +  baseURL: 'http://127.0.0.1:3000',
создай файл .env

2022-06-02 13:43 UTC, ekaterinagaltsova commented on src/components/Button/Button.jsx
> +import Stack from '@mui/material/Stack';
импорты стилей от дркгих бибок отбить пустой строкой

2022-06-02 13:44 UTC, ekaterinagaltsova commented on src/components/Button/Button.jsx
> +      <Button variant="text">Text</Button>
зачем три вида?

2022-06-02 13:46 UTC, ekaterinagaltsova commented on src/components/Header/Header.jsx
> +import News2 from '../../assets/news2.png';
это не компонент - с мал буквы

2022-06-02 14:09 UTC, ekaterinagaltsova commented on src/redux/sagas/postSaga.jsx
> +  // call,
закомменченное

2022-06-02 14:10 UTC, ekaterinagaltsova commented on src/redux/sagas/postSaga.jsx
> +import api from '../../api/api';
пустая строка перед api

2022-06-07 13:04 UTC, s-skubedin commented on src/api/api.js
> +  baseURL: 'http://127.0.0.1:3000',
api вынести в env

2022-06-07 13:04 UTC, s-skubedin commented on src/components/Card/Card.jsx
> +export default function MediaCard({ title, description, tag }) {
Каждый компонент должен быть обернут в memo

2022-06-07 13:04 UTC, s-skubedin commented on src/components/Spinner/Spinner. jsx
> +import * as React from 'react';
Почему пробел в названии файла?

2022-06-07 13:04 UTC, s-skubedin commented on src/redux/constants.js
> +export const POSTS_FAILED = 'POSTS_FAILED';
GET_POST_REQUEST
GET_POST_SUCCESS
GET_POST_FAILED

2022-06-07 13:04 UTC, s-skubedin commented on src/redux/reducers/postsReducer.jsx
> +        ...state, isFetching: true, posts: [], error: null,
Форматирование в колонку

2022-06-07 13:04 UTC, s-skubedin commented on src/redux/sagas/postSaga.jsx
> +    const { data: payload } = yield api.get('/posts');
api.get должно быть в функции, например, getPostsRequest() {...}, которая лежит в api

2022-06-07 13:04 UTC, s-skubedin commented on src/redux/sagas/postSaga.jsx
> +    const { data: payload } = yield api.get('/posts');
Используй call
yield !== await

2022-06-07 13:04 UTC, s-skubedin commented on src/redux/sagas/postSaga.jsx
> +  yield takeEvery(actionTypes.POSTS_REQUESTED, getPostSaga);
Используй takeLatest

2022-06-07 13:04 UTC, s-skubedin commented on src/redux/sagas/rootSaga.jsx
> +    call(postSaga),
Тут call не нужен, внимательно изучай документацию

2022-06-08 08:54 UTC, s-skubedin requested changes

2022-06-08 08:54 UTC, s-skubedin commented on src/pages/MainPage/MainPage.jsx
> +  } = useSelector((state) => state.posts);
Для каждого свойства свой useSelector

2022-06-08 08:54 UTC, s-skubedin commented on src/pages/MainPage/MainPage.jsx
> +export default Posts;
memo

2022-06-08 08:54 UTC, s-skubedin commented on src/redux/sagas/postSaga.jsx
> +    const { data: payload } = yield getPostsRequest();
call

2022-06-08 12:00 UTC, merged