Auth
LeontevV/leontev_final_front pull request #2
Opened 2022-06-23 10:58 UTC by LeontevV

2022-06-23 11:54 UTC, s-skubedin requested changes
зачем cat.png

2022-06-23 11:54 UTC, s-skubedin commented on src/components/AuthModal/AuthModal.jsx
> +export default function modalWindow() {
memo

2022-06-23 11:54 UTC, s-skubedin commented on src/components/LoginForm/LoginForm.jsx
> +/* eslint-disable jsx-a11y/label-has-associated-control */
Исправляй ошибки, а не отключай

2022-06-23 11:54 UTC, s-skubedin commented on src/components/LoginForm/LoginForm.jsx
> +import './LoginForm.css';
Соблюдай правила сортировки импортов

2022-06-23 11:54 UTC, s-skubedin commented on src/components/LoginForm/LoginForm.jsx
> +        initialValues={{
initialValues вынеси в константу, чтобы не создавался объект на каждый рендер

2022-06-23 11:54 UTC, s-skubedin commented on src/components/LoginForm/LoginForm.jsx
> +          values, errors, touched, handleChange, handleBlur, isValid, handleSubmit, dirty,
В колонку

2022-06-23 11:54 UTC, s-skubedin commented on src/redux/sagas/logOutSaga.jsx
> +    if (data.status === 200) {
Необходимо удалять токен всегда, даже при ошибке

2022-06-23 11:54 UTC, s-skubedin commented on src/redux/sagas/signUpSaga.jsx
> +      localStorage.setItem('token', data.headers.authorization);
При регистрации токен не создается. Должна открываться страница логина

2022-06-24 09:01 UTC, LeontevV commented on src/redux/sagas/signUpSaga.jsx
> +      localStorage.setItem('token', data.headers.authorization);
Катя сказала, что окно логина не должно всплывать после регистрации и введенных данных....

2022-06-24 11:55 UTC, merged